name: build and test and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
      # Runs every sunday 05.00 PM UTC (22.30 PM IST Equivalent). Pattern - "*(0-59 minute) *(0-23 hour) *(1-31 day of the month) *(1-12 month) *(0-6 day of the week)"
      - cron: '0 17 * * 0'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v3.4.0

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          
      # Install dotnet wasm buildtools workload
      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools
        
      # Restore Dependencies
      - name: Restore dependencies
        run: dotnet restore
        
      # Check Vulnerable Nuget Packages
      - name: Checking Vulnerable Nuget Packages
        run: dotnet list package --vulnerable --include-transitive
        
      # Check Outdated Nuget Packages
      - name: Checking Outdated Nuget Packages
        run: dotnet list package --outdated --include-transitive
        
       # Check Deprecated Nuget Packages
      - name: Checking Deprecated Nuget Packages
        run: dotnet list package --deprecated --include-transitive
        
      # Build Project
      - name: Build Solution
        run: dotnet build ./BlazorApp.sln --configuration Release --no-restore
  
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      # Checkout the code
      - uses: actions/checkout@v3.4.0

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      # Install dotnet wasm buildtools workload
      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools

      # Restore Dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build Project
      - name: Build
        run: dotnet build ./BlazorApp.sln --configuration Release --no-restore
        
      # Publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish src/BlazorApp/BlazorApp.csproj -c:Release -p:GHPages=true --no-restore -o dist/Web --nologo
        
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/Web/wwwroot
